<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ze" ignored="0" name="用户管理系统测试用例" tests="7" failures="3" timestamp="14 五月 2019 03:04:26 GMT" time="23.358" errors="0">
  <testcase name="loginTrue" time="1.408" classname="com.course.cases.LoginTest"/>
  <testcase name="loginFalse" time="0.117" classname="com.course.cases.LoginTest"/>
  <testcase name="addUser" time="0.185" classname="com.course.cases.AddUserTest">
    <failure type="org.apache.ibatis.exceptions.TooManyResultsException" message="Expected one result (or null) to be returned by selectOne(), but found: 42">
      <![CDATA[org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 42
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:81)
	at com.course.cases.AddUserTest.addUser(AddUserTest.java:35)
	at com.course.RunTestNGXml.main(RunTestNGXml.java:14)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addUser -->
  <testcase name="getUserInfo" time="0.161" classname="com.course.cases.GetUserInfoTest">
    <failure type="java.lang.AssertionError" message="expected [{&amp;quot;age&amp;quot;:21,&amp;quot;gender&amp;quot;:&amp;quot;female&amp;quot;,&amp;quot;id&amp;quot;:2,&amp;quot;isDelete&amp;quot;:1,&amp;quot;password&amp;quot;:&amp;quot;111111&amp;quot;,&amp;quot;permission&amp;quot;:1,&amp;quot;userName&amp;quot;:&amp;quot;luffy&amp;quot;}] but found [&amp;quot;[{\&amp;quot;id\&amp;quot;:2,\&amp;quot;userName\&amp;quot;:\&amp;quot;luffy\&amp;quot;,\&amp;quot;password\&amp;quot;:\&amp;quot;111111\&amp;quot;,\&amp;quot;gender\&amp;quot;:\&amp;quot;female\&amp;quot;,\&amp;quot;age\&amp;quot;:21,\&amp;quot;permission\&amp;quot;:1,\&amp;quot;isDelete\&amp;quot;:1}]&amp;quot;]">
      <![CDATA[java.lang.AssertionError: expected [{"age":21,"gender":"female","id":2,"isDelete":1,"password":"111111","permission":1,"userName":"luffy"}] but found ["[{\"id\":2,\"userName\":\"luffy\",\"password\":\"111111\",\"gender\":\"female\",\"age\":21,\"permission\":1,\"isDelete\":1}]"]
	at com.course.cases.GetUserInfoTest.getUserInfo(GetUserInfoTest.java:45)
	at com.course.RunTestNGXml.main(RunTestNGXml.java:14)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getUserInfo -->
  <testcase name="getUserList" time="0.363" classname="com.course.cases.GetUserListTest">
    <failure type="java.lang.AssertionError" message="expected [1] but found [47]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [47]
	at com.course.cases.GetUserListTest.getUserList(GetUserListTest.java:46)
	at com.course.RunTestNGXml.main(RunTestNGXml.java:14)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- getUserList -->
  <testcase name="updateUserInfo" time="10.125" classname="com.course.cases.UpdateUserInfoTest"/>
  <testcase name="deleteUserInfo" time="10.356" classname="com.course.cases.UpdateUserInfoTest"/>
</testsuite> <!-- 用户管理系统测试用例 -->
